export const projects = [
  {
    title: 'Iron Dragon: The Neon Edition',
    description: "My second finished game project which was a simple 2D Updown shooter game project that I developed along with four other students as a team project",
      image: '/images/1.png',
      tags: ['Unity3D', 'C#', 'Slack'],
    visit: 'Web_Builds\thisship_webgl\_ThisShip.html',
    source: 'https://albert-njubi.itch.io/iron-dragon',
    id: 0,
  },
  {
    title: 'Colloseum Coach',
    description:"While Intering at MassDigi I was brought on as a junior programmer for a turn based, pixel style project which was to be published on the google play store.",
    image: '/images/2.jpg',
    tags: ['Playstore', 'Unity2D'],
    visit: 'Web_Builds\gladiator_build\_CC.html',
    source: 'https://albert-njubi.itch.io/colloseum-coach',
    id: 1,
  },
  {
    title: 'About Last Knight',
    description: "The Second project I worked on for MassDigi with oversight from Dejobaan Games LLC, an indie games studio based in Boston, MA. This project was never released but it was a 3D puzzler similar to chess with a unique twist on gameplay.",
    image: '/images/3.png',
    tags: ['UnityEngine', 'C#', 'Maya3D',],
    visit: 'Web_Builds\ALK WebGl\_ALK.html',
    source: 'https://albert-njubi.itch.io/about-last-knight',
    id: 2,
  },
  {
    title: 'Loaded Against you',
    description: "4th Place winner submisson to the Becker IGDA 2016 24hr Jam: Experiment.",
    image: '/images/4.jpg',
    tags: ['UnityEngine', 'C#', 'Photoshop'],
    visit: 'https://tungthanhvu97.itch.io/loaded-against-you',
    source: 'https://tungthanhvu97.itch.io/loaded-against-you',
    id: 3,
  },
  {
    title: 'My Project Code Snippets',
    description: "This is a code repository for snippets of my code that I'm allowed to share from my projects I've worked on.",
    image: '/images/5.png',
    tags: ['Javascript', 'C++', 'C#', 'React.js', ],
    visit: 'https://github.com/Juubey/Code-Snippets',
    source: 'https://github.com/Juubey/Code-Snippets',
    id: 4,
  },
  {
    title: 'TBA',
    description: "My current project in development, more info soon.",
    image: '/images/6.png',
    tags: ['Unity2D', 'Aseprite', 'Live2D'],
    visit: 'https://github.com/Juubey/Developing-A-Game',
    source: 'https://github.com/Juubey/Developing-A-Game',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2012, text: 'Started my journey as a Web Developer', },
  { year: 2013, text: 'Developed my first couple of websites for clients in High School', },
  { year: 2014, text: 'Developed my first game', },
  { year: 2015, text: 'Receieved my certificate for Web Development', },
  { year: 2016, text: 'Got into Game Development', },
  { year: 2017, text: 'Started building games for MassDigi', },
  { year: 2018, text: 'Interned for Game Publishing Group :RudderHaven LLC', },
  { year: 2019, text: 'Published my Game Porfolio', },
  { year: 2020, text: 'Working as a freelance developer', },
];